export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_LOGOUT = 'SIGNUP_LOGOUT';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const ADD_STUDENT_MARK_SUCCESS = 'ADD_STUDENT_MARK_SUCCESS';
export const FETCH_STUDENT_MARK_SUCCESS = 'FETCH_STUDENT_MARK_SUCCESS';
export const ACCOUNT_VARIFICATION_REQUEST_SUCCESS = 'ACCOUNT_VARIFICATION_REQUEST_SUCCESS';
export const ACCOUNT_VARIFICATION_SUCCESS = 'ACCOUNT_VARIFICATION_SUCCESS';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';


export const ON_PRODUCT_START = 'ON_PRODUCT_START';
export const ON_PRODUCT_SUCCESS = 'ON_PRODUCT_SUCCESS';
export const ON_PRODUCT_DELETE = 'ON_PRODUCT_DELETE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
